// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/events/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/events/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/events/[id].put').default>>>>
    }
    '/api/events': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/events/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/events/index.post').default>>>>
    }
    '/api/reservations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/reservations/index.get').default>>>>
    }
    '/api/users/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/users/[id].patch').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/users/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}